### ISSUE TITLE
Add a check before executing the hook to ensure that `jq` is installed on the developer's device

### ISSUE THREAD

**Issue by craicoverflow** [craicoverflow/sailr#1]
## What

A [prerequisite](https://github.com/craicoverflow/sailr#prerequisites) for Sailr to work is that the developer has [jq](https://stedolan.github.io/jq/) installed.

There should be a pre-check in the script to see if `jq` is installed, and exit with a warning/message if it is not.

Something like the following sudo code.

```
if jq is not installed
	print "`commit-msg` hook failed. Please install jq."
	exit
endif
```

**Comment by yonash2** [comment]
Hi,
made a PR for this:
https://github.com/craicoverflow/sailr/pull/3
