### ISSUE TITLE
Global sailr.json file

### ISSUE THREAD

**Issue by Mte90** [craicoverflow/sailr#10]
If I don't want to include that file in all the project but want to use a global config file for all of my project it is possible?

**Comment by craicoverflow** [comment]
Hi @Mte90 - this is now possible, thanks for the idea.

Check out v0.1 on how to install sailr to your Git project.

https://github.com/craicoverflow/sailr/tree/v0.1#usage

TL;DR You can set `SAILR_CONFIG` to point to your `sailr.json` file in a custom location.

Let me know how you get on with it, I'm keen to hear from users!
