### ISSUE TITLE
Dead article link

### ISSUE THREAD

**Issue by johnjohndoe** [craicoverflow/sailr#20]
The `https://endaphelan.me/guides/git/using-git-hooks-to-enforce-conventional-commits/` link which should point to the article responds with an HTTP 404.

![image](https://user-images.githubusercontent.com/144518/97568865-648c7b00-19e7-11eb-9db4-ea4577c825f8.png)

There seems to be a copy [here](https://dev.to/craicoverflow/enforcing-conventional-commits-using-git-hooks-1o5p).

**Comment by craicoverflow** [comment]
Thanks <3 fixed now.
